name: Deploy to cPanel via FTP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          composer install --no-dev --prefer-dist --optimize-autoloader
          npm install
          npm run build

      - name: Prepare deployment files
        run: |
          # Remove files not needed in production
          rm -rf .git* .github tests node_modules

          cp .env.example .env

          # Set proper permissions for storage
          chmod -R 755 storage bootstrap/cache

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.FTP_DEPLOY_PATH }}
          protocol: ftp
          port: 21
          security: strict
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.github/*
            **/tests/*
            **/node_modules/*
            **/storage/*
            **/bootstrap/cache/*

      - name: Run post-deployment commands (via cPanel API)
        run: |
          curl -X POST \
          "https://${{ secrets.FTP_HOST }}:2083/execute/Fileman/run_cmd" \
          -u "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}" \
          -d "cd ${{ secrets.FTP_DEPLOY_PATH }} && \
              composer dump-autoload && \
              php artisan migrate --force && \
              php artisan optimize:clear && \
              chmod -R 755 storage bootstrap/cache"
