name: 🚀 FTP deploy on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy to test
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Remove cached bootstrap file
        run: sudo rm -rf bootstrap/services.php bootstrap/cache/packages.php

      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_SERVER }}
          server-dir: ${{ secrets.FTP_DEPLOY_PATH }}
